import { useEffect, useRef, useState, type RefObject } from 'react'
import { ArrowUpRight, ChevronLeft, ChevronRight } from 'lucide-react'

import { Alert, AlertDescription, AlertTitle } from '#/components/ui/alert'
import { Button } from '#/components/ui/button'
import { Spinner } from '#/components/ui/spinner'
import { loadPreviousDailyBrief } from '../data/brief-archive'
import { type DailyBrief } from '../domain/brief'
import { marketDate } from '../domain/catalyst'
import { RecommendationCard } from './brief-card'
import { formatCalendarDay, nyDateTime, nyTime } from './ny-time'

function BriefNavigation({ index, loading, onNewer, onOlder, olderDisabled }: {
  index: number
  loading: boolean
  onNewer: () => void
  onOlder: () => void
  olderDisabled: boolean
}) {
  return (
    <nav aria-label="Brief archive" className="brief-navigation">
      {/* Busy rather than disabled while loading, and focusable when disabled: disabling the
          focused button would drop keyboard focus to the page. The handler ignores a press while
          a load is in flight. */}
      <Button
        aria-busy={loading}
        disabled={olderDisabled}
        focusableWhenDisabled
        onClick={onOlder}
        size="sm"
        type="button"
        variant="ghost"
      >
        {loading ? <Spinner data-icon="inline-start" /> : <ChevronLeft data-icon="inline-start" />}
        Previous
      </Button>
      <Button disabled={index === 0 || loading} focusableWhenDisabled onClick={onNewer} size="sm" type="button" variant="ghost">
        Next<ChevronRight data-icon="inline-end" />
      </Button>
    </nav>
  )
}

export function publishedLabel(brief: Pick<DailyBrief, 'marketDate' | 'publishedAt'>): string {
  const published = new Date(brief.publishedAt)
  return marketDate(published) === brief.marketDate ? nyTime.format(published) : nyDateTime.format(published)
}

function BriefIssue({ brief, focusTarget, onSymbol }: {
  brief: DailyBrief
  focusTarget: RefObject<HTMLHeadingElement | null>
  onSymbol: (symbol: string) => void
}) {
  return (
    <>
      <header className="brief-cover">
        {/* The archive walks by market day, so the cover names that day; the publication instant
            is secondary, and can be later than a newer day's when an older issue is republished. */}
        <h2 className="brief-date" ref={focusTarget} tabIndex={-1}>
          <time dateTime={brief.marketDate}>{formatCalendarDay(brief.marketDate)}</time>
        </h2>
        {/* One quiet line under the day: when it was published, and by which model. The cover
            already names the day, so a same-day publication shows only its time; a later
            republication keeps its own date, since that is the point of showing it. */}
        <p className="brief-meta">
          <time dateTime={brief.publishedAt} title="Published">{publishedLabel(brief)}</time>
          <span aria-hidden="true"> · </span>
          <span title="Generated by">{brief.model}</span>
        </p>
      </header>
      {/* The trade lines speak for themselves, so the section is named for assistive technology
          only; an empty issue still says so in words. */}
      <section aria-label="Trades" className="brief-trades">
        {brief.recommendations.length === 0 && <h2>No trades</h2>}
        {brief.recommendations.map((recommendation, index) => (
          <RecommendationCard key={`${recommendation.symbol}-${index}`} onSymbol={onSymbol} recommendation={recommendation} />
        ))}
      </section>
      {brief.links.length > 0 && (
        <section aria-labelledby="brief-headlines-title" className="brief-headlines-section">
          <h2 id="brief-headlines-title">Headlines</h2>
          <ol className="brief-headlines">
            {brief.links.map((link) => {
              const url = new URL(link.url)
              return (
                <li key={link.url}>
                  {/* Title and snippet are third-party page text: React escapes them. With no
                      headline the host stands in as the title and the path follows on one
                      clipped line; nothing is derived from the slug, since that would put words
                      in the reader's view the page never said. The href keeps the whole URL. */}
                  <a href={link.url} rel="noreferrer" target="_blank">
                    <span className="brief-headline-title">{link.title ?? url.host}<ArrowUpRight aria-hidden="true" /></span>
                    {link.snippet && <span className="brief-headline-snippet">{link.snippet}</span>}
                    {link.title
                      ? <span className="brief-headline-host">{url.host}</span>
                      : <span className="brief-headline-host brief-headline-path">{url.pathname + url.search}</span>}
                  </a>
                </li>
              )
            })}
          </ol>
        </section>
      )}
      {/* Said once, at the foot of the brief, in the same quiet row Connect uses for its legal
          links; the Disclosures page is where it is said in full. */}
      <footer className="connect-footer brief-footer">
        <span>Not financial advice.</span>
        <a href="/disclosures">Disclosures</a>
      </footer>
    </>
  )
}

/**
 * The latest brief with the archive behind it, one issue at a time. Nothing on the site
 * produces a brief: the private Workflow publishes it into the store this reads from.
 */
export function BriefScreen({ latest, onSymbol }: { latest?: DailyBrief; onSymbol: (symbol: string) => void }) {
  const [history, setHistory] = useState<DailyBrief[]>(() => latest ? [latest] : [])
  const [index, setIndex] = useState(0)
  const [archiveEnd, setArchiveEnd] = useState(!latest)
  const [archiveFailed, setArchiveFailed] = useState(false)
  const [loading, setLoading] = useState(false)
  const current = history[index]
  // Moving between issues replaces the page under the reader, so focus follows to the new
  // issue's date rather than staying on a button that may now be disabled.
  const focusTarget = useRef<HTMLHeadingElement>(null)
  const [moved, setMoved] = useState(false)
  useEffect(() => {
    if (moved) focusTarget.current?.focus()
  }, [index, moved])

  const openOlder = async () => {
    if (loading) return
    if (history[index + 1]) {
      setIndex(index + 1)
      setMoved(true)
      return
    }
    if (!current) return
    setArchiveFailed(false)
    setLoading(true)
    try {
      const previous = await loadPreviousDailyBrief(current.marketDate)
      if (!previous) {
        setArchiveEnd(true)
        return
      }
      if (previous.marketDate >= current.marketDate) throw new Error('Brief archive returned an out-of-order result')
      setHistory((loaded) => [...loaded, previous])
      setIndex(index + 1)
      setMoved(true)
    } catch {
      setArchiveFailed(true)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="brief-screen">
      {latest && (
        <BriefNavigation
          index={index}
          loading={loading}
          onNewer={() => { setArchiveFailed(false); setIndex(Math.max(0, index - 1)); setMoved(true) }}
          onOlder={() => void openOlder()}
          olderDisabled={archiveEnd && !history[index + 1]}
        />
      )}
      {archiveFailed && (
        <Alert className="archive-error" variant="destructive">
          <AlertTitle>Archive unavailable</AlertTitle>
          <AlertDescription>Previous briefs could not be loaded.</AlertDescription>
        </Alert>
      )}
      {current
        ? <BriefIssue brief={current} focusTarget={focusTarget} onSymbol={onSymbol} />
        : (
            <section className="brief-empty">
              <h2>No brief yet</h2>
              <p>The first brief lands with the next trading morning's run.</p>
            </section>
          )}
    </div>
  )
}
